
<?php $calendarCollection = Mage::getModel('compta_calendar/calendar')->getCollection(); ?>

<style>


    .ui-state-active {
        border: 2px dashed #000 !important;
        background: #93c3cd url("/skin/adminhtml/default/default/images/jquery/ui/ui-bg_diagonals-small_50_93c3cd_40x40.png") 50% 50% repeat !important;
        font-weight: bold !important;

        color: #333333 !important;
    }

    <?php foreach($calendarCollection as $cal): ?>
    <?php $customer = Mage::getModel('compta_customer/customer')->load($cal->getCustomerId()); ?>
    .ui-datepicker-calendar td a.customer-<?php echo md5($customer->getId()); ?> {
        background: <?php echo $customer->getColor(); ?> !important;
    }
    <?php endforeach; ?>

</style>
<div style="float:left;">
    <div id="timeslot_calendar"></div>
</div>
<div id="saisie" style="float:right;width:36%; ">

    <div class="entry-edit no-display" id="edit-date">
        <div class="entry-edit-head">
            <h4 style="float:none; padding: 7px 0;text-align:center; font-size:16px;" class="icon-head head-edit-form fieldset-legend"><span class="date">Le 29/03/16</span></h4>
        </div>
        <fieldset>
            <form method="post" action="<?php echo $this->helper("adminhtml")->getUrl("adminhtml/calendar_index/save"); ?>">
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                <input type="hidden" id="date-ymd" name="date-ymd" value=""/>
                <table width="100%" cellspacing="0">
                    <tbody>
                    <?php foreach (Mage::getModel('compta_customer/customer')->getCollection() as $customer): ?>
                        <tr rel="<?php echo $customer->getId(); ?>">
                            <td style="padding:4px 0">

                                <div class="entry">
                                    <div class="customer-name" style="width:44%; float:left;">
                                        <?php echo $customer->getNom(); ?>
                                    </div>
                                    <select style="float:left" rel="<?php echo $customer->getId(); ?>" name="hours[<?php echo $customer->getId(); ?>]">
                                        <?php foreach (array(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12) as $h): ?>
                                            <option value="<?php echo $h; ?>"><?php echo number_format($h,1); ?>
                                                heure<?php if ($h > 1): ?>s<?php endif; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tr>
                        <td><br/>
                            <button style="margin-left:44%;padding:2px 20px">Valider</button>
                        </td>
                    </tr>
                </table>
            </form>
        </fieldset>
    </div>

</div>
<script type="text/javascript">
    jQuery(function () {

        jQuery(document).tooltip({track: true});


        Number.prototype.padZero = function (len) {
            var s = String(this), c = '0';
            len = len || 2;
            while (s.length < len) s = c + s;
            return s;
        }

        Array.prototype.getUnique = function(){
            var u = {}, a = [];
            for(var i = 0, l = this.length; i < l; ++i){
                if(u.hasOwnProperty(this[i])) {
                    continue;
                }
                a.push(this[i]);
                u[this[i]] = 1;
            }
            return a;
        }

        var calendar = [
        <?php foreach($calendarCollection as $calendar):?>
            <?php $customer = Mage::getModel('compta_customer/customer')->load($calendar->getCustomerId()); ?>
            {
                "customerId": "<?php echo $customer->getId(); ?>",
                "customerName": "<?php echo $customer->getNom(); ?>",
                "customerClass": "<?php echo md5($customer->getId()); ?>",
                "dates": [
                    <?php $dates = $this->helper('core')->jsonDecode($calendar->getValues()); ?>
                    <?php foreach($dates as $day => $nbHour):?>
                        {"day":'<?php echo $day; ?>', "hour": <?php echo (string)$nbHour; ?>},
                    <?php endforeach; ?>
                ]
            },
        <?php endforeach; ?>
        ];

        var daySelected = [];

        for (var i = 0; i < calendar.length; i++) {
            var obj = calendar[i];

            if ((obj.dates).length) {
                jQuery.each(obj.dates, function (d, date) {
                   // daySelected.push(date);
                });
            }
        }


        jQuery('#timeslot_calendar').datepick({
                dateFormat: 'yyyy-mm-dd',
                altFormat: 'yyyy-mm-dd',
                altField: '#timeslot',
                monthsToShow: [3, 3],
                showOtherMonths: true,
                multiSelect: false,
                selectDefaultDate: false,
                firstDay: 1,
                renderer: jQuery.datepick.themeRollerRenderer,
                onShow: function () {
                    for (var i = 0; i < calendar.length; i++) {
                        var obj = calendar[i];
                        if ((obj.dates).length) {

                            for (var d = 0; d < (obj.dates).length; d++) {
                                day = (obj.dates)[d].day;
                                hour = (obj.dates)[d].hour;

                                foo = new Date(day + ' 12:00:00');
                                timestamp = (foo.getTime() / 1000) + '000';
                                if (jQuery('td a.dp' + timestamp)) {

                                    var actualTitle = jQuery('td a.dp' + timestamp).prop('title');

                                    if(hour > 0) {
                                        jQuery('td a.dp' + timestamp).addClass('customer-' + obj.customerClass);
                                        if(typeof actualTitle !== "undefined") {
                                            if(actualTitle.length == 0) {
                                                jQuery('td a.dp' + timestamp).prop('title', obj.customerName + ' ' + hour + "H");
                                            } else {

                                                newTitle = actualTitle + ' + ' + obj.customerName + ' ' + hour + "H";
                                                newTitle = newTitle.split(' + ').getUnique().join(' + ');

                                                jQuery('td a.dp' + timestamp).prop('title', newTitle);

                                            }
                                        }

                                    }
                                }

                            }
                        }
                    }
                },
                onSelectDate: function (elem, target) {
                    var classList = jQuery(target).attr('class').split(/\s+/);
                    jQuery.each(classList, function (index, item) {
                        var re = /^dp(\d{13})$/i;
                        if (results = item.match(re)) {
                            var timestamp = results[1];


                            var date = new Date(timestamp * 1);
                            var year = date.getFullYear().padZero();
                            var month = (date.getMonth() + 1).padZero();
                            var day = date.getDate().padZero();

                            jQuery('#edit-date').removeClass('no-display');
                            jQuery('#edit-date .date').text(day + "/" + month + "/" + year);
                            jQuery('#edit-date #date-ymd').val (year + "-" + month + "-" + day);

                            ///////////////////////////

                            jQuery('#edit-date select').val(0);

                            for (var i = 0; i < calendar.length; i++) {
                                var obj = calendar[i];
                                if ((obj.dates).length) {

                                    for (var d = 0; d < (obj.dates).length; d++) {
                                        hour = (obj.dates)[d].hour;
                                        if(hour>0 && (obj.dates)[d].day == (year + "-" + month + "-" + day)) {
                                            jQuery('#edit-date select[rel='+(obj.customerId)+']').val(hour)
                                        }
                                    }
                                }
                            }
                        }
                    });
                }
            }, jQuery.datepick.regionalOptions['fr']
        );

        var selected = jQuery('#timeslot').val() || 0;


        /*
         jQuery('td a').on('click',function(ev) {


         return;
         var classList = jQuery(this).attr('class').split(/\s+/);
         jQuery.each(classList, function(index, item) {
         var re = /^dp(\d{13})$/i;
         if(results = item.match(re)){
         var timestamp = results[1];
         console.log(timestamp)

         var date = new Date(timestamp*1000);
         var year = date.getFullYear();
         var month = date.getMonth() + 1;
         var day = date.getDate();

         jQuery('#edit-date').removeClass('no-display');
         jQuery('#edit-date .date').text(day + "/" + month + "/" + year)
         }
         });


         });  */


    });
</script>
